### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by meredithcat** [Sukhrobjon/CS-2.2-Challenges#1]
Challenge 1 Feedback: 6/20
Feedback based on Challenge 1 Rubric

- Solution: 0
  - Does not run on sample input without errors

- Documentation: 2
  - Include input/output and runtime in docstrings
  - Remove commented out code to improve clarity

- Organization: 3
  - Put main challenge_1 code in a main function rather than in global scope
  - Suggestion: Remove "main" code from graph.py

- Testing: 1
  - Add tests for Graph and file handling

**Comment by aespaldi** [comment]
**RESUBMIT**
Challenge 1 Feedback : 

Overall: 13/20 Pass

Feedback based on Challenge 1 Rubric: 

- Works: 6
- Documentation: 2
  - No attribution given for code copied from tutorial sample (add a line at the top) 
- Code Organization: 3
- Testing: 2
